resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/concourse/flight-school
    branch: master

- name: java-buildpacker-docker-image
  type: docker-image
  source:
    repository: jrfranzen/java-buildpacker-example
    username: 
    password: 

jobs:
- name: build-cached-image
  plan:
  - get: flight-school
  - task: build-cached-image-workspace
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu

      outputs:
      - name: workspace

      inputs:
      - name: flight-school

      run:
        path: /bin/bash
        args:
        - -c
        - |
          output_dir=workspace

          cat << EOF > "${output_dir}/Dockerfile"
          FROM ruby

          ADD flight-school /tmp/flight-school
          RUN /usr/local/bin/bundle install --gemfile=/tmp/flight-school/Gemfile
          
          EOF

          cp -R ./flight-school "${output_dir}/flight-school"



  - put: java-buildpacker-docker-image
    params:
      build: workspace

- name: build-pack-create
  plan:
  - get: java-buildpacker-docker-image
    passed: [build-cached-image]
    trigger: true
  - get: flight-school
    passed: [build-cached-image]
  - task: run-tests
    image: java-buildpacker-docker-image
    config:
      platform: linux
      inputs:
      - name: flight-school
      run:
        dir: flight-school
        path: /bin/bash
        args:
        - -c
        - |
          output_dir=workspace

          git clone https://github.com/cloudfoundry/java-buildpack.git
          cd java-buildpack
          git fetch origin --tags
          git checkout tags/v4.11 -b b4.11_oracle
          export VER="version: 4.4.1_0"
          sed -i "s/version: ''/$VER/" config/app_dynamics_agent.yml
          /usr/local/bin/bundle install
          /usr/local/bin/bundle exec rake clean package OFFLINE=true PINNED=true